modLoader="javafml"
loaderVersion="[40,)"
license="AGPL-3.0"

[[mods]]
modId="compressed_grass"
version="6.2.0"
displayName="Compressed Grass:Reborn"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://github.com/Adenx0/Compressed_Grass_Reborn"
authors="Grey Wind"

[[dependencies.compressed_grass]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




