modLoader="javafml"
loaderVersion="[45,)"
license="GNU Affero General Public License Version 3 (AGPL v3)"

[[mods]]
modId="compressed_grass"
version="0.1.0"
displayName="CompressedGrass"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://github.com/Grey-Wind/CompressedGrassReborn-Forge"
authors="Sunrise Studio - Grey Wind"

[[dependencies.compressed_grass]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"



[[dependencies.compressed_grass]]
    modId="curios_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.compressed_grass]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

