modLoader="javafml"
loaderVersion="[47,)"
license="GNU Affero General Public License Version 3 (AGPL v3)"

[[mods]]
modId="compressed_grass"
version="0.1.0"
displayName="CompressedGrass"
displayURL="https://github.com/Grey-Wind/CompressedGrassReborn-Forge"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Sunrise Studio - Grey Wind"
description="A mod that continuously compresses grass."

[[dependencies.compressed_grass]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




