modLoader="javafml"
loaderVersion="[36,)"
license="GPL-3.0"

[[mods]]
modId="compressed_grass"
version="5.4.1"
displayName="Compressed Grass:Reborn"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://github.com/Adenx0/Compressed_Grass_Reborn"
authors="AT Studio"
description='''
Compress the grass until you defeat the author.
'''

[[dependencies.compressed_grass]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




